/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sajin

object Sajin {
    /**
     * Compares pixel by pixel, each pixel must be in a range of the
     * standard deviation.
     */
    fun softCompare(x: String, y: String, std: Int): Float {
        val a = 10.0f
        val b = 1.0f

        return a / b
    }

    /**
     * Gets the average value of each pixel, and if the result is inside
     * the range given by the standard deviation then the pixel will be
     * considered as a matched pixel.
     */
    fun midCompare(x: String, y: String, std: Int): Float {
        val a = 10.0f
        val b = 1.0f

        return a / b
    }

    /**
     * Compares pixel by pixel, each pixel must be equal to be counted
     * as a matched pixel.
     */
    fun hardCompare(x: String, y: String): Float {
        return 0.1f
    }
}
