/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sajin

import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
    @Test fun softCompareMethodWorks() {
        val value = Sajin.softCompare("", "", 20)
        assertEquals(value, 10f)
    }

    @Test fun hardCompareMethodWorks() {
        val value = Sajin.hardCompare("", "")
        assertEquals(value, 0.1f)
    }
}
